## feat_matrix 

1. reduce the size of each feature matrix for each .vtp fiber bundle (basis of a percentage 10)
2. attach label to each feat_matrix.h5 file using label mapping
3. combine the 54 tracts mentioned in the supplementary of the paper

In [1]:
import h5py
AF_left_feat_path = "/media/ang/Data/unnerve_data/779370/779370_T_AF_left_featMatrix.h5"

# read feat_matrix
with h5py.File(AF_left_feat_path, "r") as f:
        # List all groups
        print("Keys: %s" % f.keys())
        h_keys = list(f.keys())[0]

        # Get the data
        data = list(f[h_keys])
        print(len(data))
        print(len(f[h_keys][0]))

        print(len(f[h_keys][0][0:10]))
        print(type(f[h_keys]))
        print(int(len(f[h_keys])/20))
        compressed_data = f[h_keys][0: int(len(f[h_keys]))]
        print(type(compressed_data))
        

# reduce the size of feature_matrix



Keys: <KeysViewHDF5 ['feat']>
44656
30
10
<class 'h5py._hl.dataset.Dataset'>
2232
<class 'numpy.ndarray'>


In [3]:
label_mapping_72 = pd.read_csv("/home/ang/Documents/GitHub/DeepWMA/labels_reference.csv", names=["label_names", "label_array"])
# label_mapping_54 =  pd.read_csv("/home/ang/Documents/GitHub/DeepWMA/labels_reference_54.csv", names=["label_names", "label_array"])
label_mapping_72['label_names'] = label_mapping_72['label_names'].astype('|S')


In [4]:
label_mapping_72.loc[label_mapping_72.label_names == bytes('T_PREF_right', 'utf-8'),'label_array'].values[0]

67

In [5]:

# feat_array = np.random.random(size=(44656, 30, 30, 3))
label_hdf_dtype = np.dtype([('label_names', 'a30'), ('label_values', int), ('label_array', int)])
# see whether it is required
feat_hdf_dtype = np.dtype(['feat', np.ndarray])


subject_ID="779370"
# pass this subject ID from the bash file code
output_folder="/media/ang/Data/unnerve_data/".format(subject_ID)
fiber_tract='T_AF_LEFT'
# either search for a list of names in the whole string path (find and replace type)

feat_matrix= "/media/ang/Data/unnerve_data/779370/779370_T_AF_left_featMatrix.h5"

for filename in os.listdir("/media/ang/Data/unnerve_data/779370/"):
    if filename.endswith((".h5")):
        if ".vtk" not in filename:
            if "atlas" not in filename:
                tract_name = filename.replace(subject_ID + "_T_", "").replace("_featMatrix.h5", "")
                tract_label = label_mapping_72.loc[label_mapping_72.label_names == bytes(tract_name, 'utf-8'),'label_array'].item()
                print(tract_name, tract_label)

                # limit the size of the numpy array to 5% of the array so that the error of big size can be resolved 
    else: 
        continue
        



AF_left 0
AF_right 1
ATR_left 2
ATR_right 3
CA 4
CC_1 5
CC_2 6
CC_3 7
CC_4 8
CC_5 9
CC_6 10
CC_7 11
CC 12
CG_right 14
CST_left 15
CST_right 16
FPT_left 17
FPT_right 18
FX_left 19
FX_right 20
ICP_left 21
ICP_right 22
IFO_left 23
IFO_right 24
ILF_left 25
ILF_right 26
MLF_left 28
MLF_right 29
OR_left 30
OR_right 31
POPT_left 32
POPT_right 33
SCP_left 34
SCP_right 35
SLF_III_left 36
SLF_III_right 37
SLF_II_left 38
SLF_II_right 39
SLF_I_left 40
STR_left 56
STR_right 57
ST_FO_left 42
ST_FO_right 43
ST_OCC_left 44
ST_OCC_right 45
ST_PAR_left 46
ST_PAR_right 47
ST_POSTC_left 48
ST_POSTC_right 49
ST_PREC_left 50
ST_PREC_right 51
ST_PREF_left 52
CG_left 13
MCP 27
SLF_I_right 41
ST_PREF_right 53
ST_PREM_left 54
ST_PREM_right 55
T_OCC_left 58
T_OCC_right 59
T_PAR_left 60
T_PAR_right 61
T_POSTC_left 62
T_POSTC_right 63
T_PREC_left 64
T_PREC_right 65
T_PREF_left 66
T_PREF_right 67
T_PREM_left 68
T_PREM_right 69
UF_left 70
UF_right 71


In [6]:
# limit the size of the numpy array to 5% of the array so that the error of big size can be resolved 
reducing_fraction = 0.05
feat_label_value = 1
feat_label_name = 'AF_right'
feat_label=np.empty(feat_array.shape[0], dtype=label_hdf_dtype)
# h5_feat_label = h5py.File('.h5', 'w')
# h5_feat_label.create_dataset('dataset_1', data=feat_label)


In [7]:
# feat_label.fill((bytes(feat_label_name, 'utf-8'), feat_label_value, feat_label_value))
feat_label.fill(('AF_right', feat_label_value, feat_label_value))

In [8]:
feat_label

array([(b'AF_right', 1, 1), (b'AF_right', 1, 1), (b'AF_right', 1, 1), ...,
       (b'AF_right', 1, 1), (b'AF_right', 1, 1), (b'AF_right', 1, 1)],
      dtype=[('label_names', 'S30'), ('label_values', '<i8'), ('label_array', '<i8')])

In [9]:
feat_label[0:int(0.05*feat_label.shape[0])].shape
feat_array[0:int(reducing_fraction*feat_array.shape[0])].shape


(2232, 30, 30, 3)

In [10]:
feat_array_reduced = feat_array[0:int(reducing_fraction*feat_array.shape[0])]
feat_array_reduced.shape
feat_label_reduced = feat_label[0:int(reducing_fraction*feat_array.shape[0])]

In [11]:
# convert to .h5 from numpy array

h5_feat_label = h5py.File("/media/ang/Data/data/779370/AF_right_labels.h5", 'w')
h5_feat_label.create_dataset("/media/ang/Data/data/779370/AF_right_labels.h5", data=feat_label_reduced)

h5_feat_array = h5py.File("/media/ang/Data/data/779370/AF_right_featMatrix.h5", 'w')
h5_feat_array.create_dataset("/media/ang/Data/data/779370/AF_right_featMatrix.h5", data=feat_array_reduced)


<HDF5 dataset "AF_right_featMatrix.h5": shape (2232, 30, 30, 3), type "<f8">

In [17]:
# for CC_1 with its featurea array and feat label
CC_1_feat_path = "/media/ang/Data/unnerve_data/779370/779370_T_CC_1_featMatrix.h5"

# read feat_matrix
with h5py.File(CC_1_feat_path, "r") as f:
        # List all groups
        print("Keys: %s" % f.keys())
        h_keys = list(f.keys())[0]

        # Get the data
        # data = list(f[h_keys])
        data = f.get('feat')[()]

Keys: <KeysViewHDF5 ['feat']>
[[[[ 15.35179996  16.60079956 -14.50759983]
   [ 14.23649979  18.50139999 -11.70650005]
   [ 14.23649979  18.50139999 -11.70650005]
   ...
   [ 14.23649979  18.50139999 -11.70650005]
   [ 14.23649979  18.50139999 -11.70650005]
   [ 15.35179996  16.60079956 -14.50759983]]

  [[-11.3657999   27.36170006 -12.38759995]
   [-11.07960033  27.10510063 -11.66189957]
   [-11.07960033  27.10510063 -11.66189957]
   ...
   [-11.07960033  27.10510063 -11.66189957]
   [-11.07960033  27.10510063 -11.66189957]
   [-11.3657999   27.36170006 -12.38759995]]

  [[ 15.35179996  16.60079956 -14.50759983]
   [ 14.23649979  18.50139999 -11.70650005]
   [ 14.23649979  18.50139999 -11.70650005]
   ...
   [ 14.23649979  18.50139999 -11.70650005]
   [ 14.23649979  18.50139999 -11.70650005]
   [ 15.35179996  16.60079956 -14.50759983]]

  ...

  [[-11.3657999   27.36170006 -12.38759995]
   [-11.07960033  27.10510063 -11.66189957]
   [-11.07960033  27.10510063 -11.66189957]
   ...
   [-

In [18]:
# for CC_1 with its featurea array and feat label
CC_1_feat_path = "/media/ang/Data/unnerve_data/779370/779370_T_CC_1_featMatrix.h5"

# read feat_matrix
with h5py.File(CC_1_feat_path, "r") as f:
        # List all groups
        print("Keys: %s" % f.keys())
        h_keys = list(f.keys())[0]

        # Get the data
        # data = list(f[h_keys])
        data = f.get('feat')[()]
        cc_feat_array = data
        
# print(type(np_data))
# reduce the size of feature_matrix
# cc_feat_array = feat
cc_feat_label_value = 5
cc_feat_label_name = 'CC_1'
cc_feat_label=np.empty(cc_feat_array.shape[0], dtype=label_hdf_dtype)


# limit the size of the numpy array to 5% of the array so that the error of big size can be resolved 
reducing_fraction = 0.05
# h5_feat_label = h5py.File('.h5', 'w')
# h5_feat_label.create_dataset('dataset_1', data=feat_label)

cc_feat_label.fill((cc_feat_label_name, cc_feat_label_value, cc_feat_label_value))
n_tracts = int(reducing_fraction*cc_feat_array.shape[0])
cc_feat_label_reduced = cc_feat_label[0:n_tracts]

cc_feat_array_reduced = cc_feat_array[0:n_tracts]

h5_feat_label = h5py.File("/media/ang/Data/data/779370/CC_1_labels.h5", 'w')
h5_feat_label.create_dataset("/media/ang/Data/data/779370/CC_labels.h5", data=cc_feat_label_reduced)
h5_feat_label.close()

h5_feat_array = h5py.File("/media/ang/Data/data/779370/CC_1_featMatrix.h5", 'w')
h5_feat_array.create_dataset("/media/ang/Data/data/779370/CC_1_featMatrix.h5", data=cc_feat_array_reduced)
h5_feat_array.close()

Keys: <KeysViewHDF5 ['feat']>


In [19]:
cc_feat_label_reduced.shape

(699,)

In [20]:
# merge cc and AF (appending numpy array)

feat_label = np.append(feat_label_reduced, cc_feat_label_reduced, axis=0)
feat_array = np.append(feat_array_reduced, cc_feat_array_reduced, axis = 0)
print(feat_label.shape, feat_array.shape)

(2931,) (2931, 30, 30, 3)


In [37]:
feat_label

array([(b'AF_right', 1, 1), (b'AF_right', 1, 1), (b'AF_right', 1, 1), ...,
       (b'CC_1', 5, 5), (b'CC_1', 5, 5), (b'CC_1', 5, 5)],
      dtype=[('label_names', 'S30'), ('label_values', '<i8'), ('label_array', '<i8')])

In [32]:
feat_label['label_names']

array([b'AF_right', b'AF_right', b'AF_right', ..., b'CC_1', b'CC_1',
       b'CC_1'], dtype='|S30')

In [36]:
h5_feat_array.close()
h5_feat_array = h5py.File("/media/ang/Data/data/779370/af_cc_featMatrix.h5", 'w')
h5_feat_array.create_dataset('feat', data=feat_array)
h5_feat_array.close()

h5_feat_label.close()
h5_feat_label =  h5py.File("/media/ang/Data/data/779370/af_cc_label.h5", 'w')
h5_feat_label.create_dataset('label_array', data=feat_label['label_array'])# type: ignore
h5_feat_label.create_dataset('label_values', data=feat_label['label_values'])  # type: ignore
h5_feat_label.create_dataset('label_names', data=feat_label['label_names'])  # type: ignore

h5_feat_label.close()

In [ ]:
with h5py.File("/media/ang/Data/data/779370/af_cc_label.h5", "r") as f:
        # List all groups
        print("Keys: %s" % f.keys())
        h_keys = list(f.keys())[0]
        print(f[h_keys][()])

        # Get the data
        # data = list(f[h_keys])
        # data = f.get('feat').value

In [ ]:
with h5py.File("/home/ang/Documents/GitHub/DeepWMA/data/999999/999999_labels.h5", "r") as f:
        # List all groups
        print("Keys: %s" % f.keys())
        h_keys = list(f.keys())[0]
        print(f[h_keys])
        data = list(f[h_keys])
        print(data)


In [ ]:
print(os.path.getsize('/media/ang/Data/data/779370/af_cc_featMatrix.h5')/(1024*1024))

## labels

1. after step 2 above
2. combine the labels for each tract with limited fibers